apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-swaggerimporter
  namespace: services
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: client_id
    azure.workload.identity/tenant-id: tenant_id
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: swaggerimporter-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: swaggerimporter-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: workload-identity-swaggerimporter
  namespace: services
roleRef:
  kind: ClusterRole
  name: swaggerimporter-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaggerimporter
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      name: swaggerimporter
  template:
    metadata:
      labels:
        name: swaggerimporter
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-swaggerimporter
      containers:
      - name: swaggerimporter
        image: deggja/swaggerimporter:latest
        args:
          - "--leader-elect=true"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi